steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1200 && cd api_server && gcloud app deploy --version $COMMIT_SHA']
- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "asia.gcr.io/${PROJECT_ID}/appengine/default.$COMMIT_SHA",
         "-s", "${_CLOUD_SQL_CONNECTION_NAME}",
         "--", "bundle", "exec", "rake", "db:migrate"]
timeout: '1800s'
