steps:
- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/macro-market-336309/appengine/default:latest",
         "-s", "macro-market-336309:asia-northeast1:hojokin-dock-production",
         "--", "bundle", "exec", "rake", "db:migrate"]
  env:
    - PRODUCTION_DATABASE_USER=${_PRODUCTION_DATABASE_USER}
    - PRODUCTION_DATABASE_PASSWORD=${_PRODUCTION_DATABASE_PASSWORD}
    - CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}
timeout: '1800s'
