steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['cd api_server']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['app', 'deploy']
  env:
    - PRODUCTION_DATABASE_USER=${_PRODUCTION_DATABASE_USER}
    - PRODUCTION_DATABASE_PASSWORD=${_PRODUCTION_DATABASE_PASSWORD}
    - PRODUCTION_FIREBASE_PROJECT_ID=${_PRODUCTION_FIREBASE_PROJECT_ID}
    - PRODUCTION_FIREBASE_API_KEY=${_PRODUCTION_FIREBASE_API_KEY}
    - CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}
    - PRODUCTION_SCRAPING_BUCKET=${_PRODUCTION_SCRAPING_BUCKET}
    - SLACK_API_TOKEN=${_SLACK_API_TOKEN}
  timeout: '1200s'
timeout: '1200s'
