steps:
- name: 'curlimages/curl'
  args: ['-X','POST',
         '--data-urlencode', '"payload={\"text\": \"*[hojokin_dock/web_front]*\nBuild Started :gear: $BUILD_ID\"}"',
         '${_SLACK_WEBHOOK_URL}']
- name: node:14.17.0
  entrypoint: yarn
  dir: 'web_front'
  args: ['install']
- name: 'bash'
  entrypoint: bash
  dir: 'web_front'
  args: ['-c', 'touch .env
         && echo "PRODUCTION_API_KEY=$_PRODUCTION_API_KEY" >> .env
         && echo "PRODUCTION_AUTH_DOMAIN=$_PRODUCTION_AUTH_DOMAIN" >> .env
         && echo "PRODUCTION_PROJECT_ID=$_PRODUCTION_PROJECT_ID" >> .env
         && echo "PRODUCTION_STORAGE_BUCKET=$_PRODUCTION_STORAGE_BUCKET" >> .env
         && echo "PRODUCTION_MESSAGING_SNDER_ID=$_PRODUCTION_MESSAGING_SNDER_ID" >> .env
         && echo "PRODUCTION_APP_ID=$_PRODUCTION_APP_ID" >> .env
         && echo "PRODUCTION_MEASUREMENT_ID=$_PRODUCTION_MEASUREMENT_ID" >> .env']
- name: node:14.17.0
  entrypoint: yarn
  dir: 'web_front'
  args: ['generate']
- name: gcr.io/${PROJECT_ID}/firebase
  dir: 'web_front'
  args: ['deploy', '--project=${PROJECT_ID}', '--only=hosting']
- name: 'curlimages/curl'
  args: ['-X','POST',
         '--data-urlencode', '"payload={\"text\": \"*[hojokin_dock/web_front]*\nBuild Completed $BUILD_ID\"}"',
         '${_SLACK_WEBHOOK_URL}']
timeout: '1800s'
