steps:
- name: node
  entrypoint: yarn
  args: ['install']
- name: node
  entrypoint: yarn
  args: ['generate']
  env:
    - 'PRODUCTION_API_KEY=${_PRODUCTION_API_KEY}'
    - 'PRODUCTION_AUTH_DOMAIN=${_PRODUCTION_AUTH_DOMAIN}'
    - 'PRODUCTION_PROJECT_ID=${_PRODUCTION_PROJECT_ID}'
    - 'PRODUCTION_STORAGE_BUCKET=${_PRODUCTION_STORAGE_BUCKET}'
    - 'PRODUCTION_MESSAGING_SNDER_ID=${_PRODUCTION_MESSAGING_SNDER_ID}'
    - 'PRODUCTION_APP_ID=${_PRODUCTION_APP_ID}'
    - 'PRODUCTION_MEASUREMENT_ID=${_PRODUCTION_MEASUREMENT_ID}'
- name: gcr.io/macro-market-336309/firebase
  args: ['deploy', '--project=macro-market-336309', '--only=hosting']
timeout: '1800s'
