openapi: 3.0.0
info:
  version: 1.0.0
  title: Hojokin Dock API
  description: '補助金ドックのAPIドキュメント'
servers:
  - url: 'http://localhost:3000'
tags:
  - name: subsidy
    description: 補助金情報
  - name: ministry
    description: 省庁
  - name: prefecture
    description: 都道府県
  - name: city
    description: 市長区村
paths:
  "/subsidies":
    get:
      tags:
      - subsidy
      summary: 補助金情報一覧
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                - subsidies
                properties:
                  subsidies:
                    type: array
                    items:
                      "$ref": "#/components/schemas/subsidy"
  "/subsidies/{id}":
    parameters:
    - name: id
      in: path
      required: true
      description: subsidyのid
      schema:
        type: integer
    get:
      tags:
      - subsidy
      summary: 補助金情報詳細
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/subsidy"
  "/ministries":
    get:
      tags:
      - ministry
      summary: 省庁一覧
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                - ministries
                properties:
                  ministries:
                    type: array
                    items:
                      "$ref": "#/components/schemas/ministry"
  "/prefectures":
    get:
      tags:
      - prefecture
      summary: 都道府県一覧
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                - prefectures
                properties:
                  prefectures:
                    type: array
                    items:
                      "$ref": "#/components/schemas/prefecture"
  "/prefectures/{id}/cities":
    parameters:
    - name: id
      in: path
      required: true
      description: prefectureのid
      schema:
        type: integer
    get:
      tags:
      - city
      summary: 市長区村一覧
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                - cities
                properties:
                  cities:
                    type: array
                    items:
                      "$ref": "#/components/schemas/city"
components:
  schemas:
    subsidy:
      type: object
      required:
        - id
        - title
        - url
        - start_from
        - end_to
        - ministry
        - prefecture
        - city
      properties:
        id:
          type: integer
          description: id
          example: 1
        title:
          type: string
          description: 補助金名
          example: IT導入補助金
        url:
          type: string
          description: URL
          example: https://www.it-hojo.jp/applicant/
        start_from:
          type: string
          format: date
          description: 募集期間（開始日）
          example: '2022-01-01'
        end_to:
          type: string
          format: date
          description: 募集期間（終了日）
          example: '2022-02-01'
        price_max:
          type: integer
          description: 最大支援金額
          example: 60000000
        support_ratio_min:
          type: string
          description: 支援割合（最小）
          example: 1/2
        support_ratio_max:
          type: string
          description: 支援割合（最大）
          example: 3/4
        level:
          type: integer
          description: 申請難易度
          example: 4
        deatil:
          type: string
          description: 詳細文章
          example: 新型コロナウイルス感染症の影響が長期化し、当面の需要や売上の回復が期待し難い中、ウィズコロナ・ポストコロナの時代の経済社会の変化に対応するために新分野展開、業態転換、事業・業種転換、事業再編又はこれらの取組を通じた規模の拡大等、思い切った事業再構築に意欲を有する中小企業等の挑戦を支援することで、日本経済の構造転換を促すことを目的とします。※申請の受付は11月17日より開始となりました。
        ministry:
          "$ref": "#/components/schemas/ministry"
        prefecture:
          "$ref": "#/components/schemas/prefecture"
        city:
          "$ref": "#/components/schemas/city"
        business_categories:
          type: array
          items:
            "$ref": "#/components/schemas/business_category"
    ministry:
      type: object
      nullable: true
      required:
        - id
        - name
        - logo_url
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 省庁名
          example: 経済産業省
        logo_url:
          type: string
          description: URL
          example: https://example.com/logo.png
    prefecture:
      type: object
      nullable: true
      required:
        - id
        - name
        - logo_url
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 都道府県名
          example: 東京都
        logo_url:
          type: string
          description: URL
          example: https://example.com/logo.png
    city:
      type: object
      nullable: true
      required:
        - id
        - name
        - logo_url
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 市町区村名
          example: 千代田区
        logo_url:
          type: string
          description: URL
          example: https://example.com/logo.png
    business_category:
      type: object
      nullable: true
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 業種名
          example: 製造業
