openapi: 3.0.0
info:
  version: 1.0.0
  title: Hojokin Dock API
  description: "補助金ドックのAPIドキュメント"
servers:
  - url: "http://localhost:3000"
tags:
  - name: admin/user
    description: ユーザー管理
  - name: company
    description: 会社
  - name: subsidy
    description: 補助金情報
  - name: ministry
    description: 省庁
  - name: prefecture
    description: 都道府県
  - name: city
    description: 市長区村
  - name: business_category
    description: 業種
paths:
  "/subsidies":
    get:
      tags:
        - subsidy
      summary: 補助金情報一覧
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - subsidies
                properties:
                  subsidies:
                    type: array
                    items:
                      "$ref": "#/components/schemas/subsidy"
  "/subsidies/{id}":
    parameters:
      - name: id
        in: path
        required: true
        description: subsidyのid
        schema:
          type: integer
    get:
      tags:
        - subsidy
      summary: 補助金情報詳細
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/subsidy"
  "/ministries":
    get:
      tags:
        - ministry
      summary: 省庁一覧
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - ministries
                properties:
                  ministries:
                    type: array
                    items:
                      "$ref": "#/components/schemas/ministry"
  "/prefectures":
    get:
      tags:
        - prefecture
      summary: 都道府県一覧
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - prefectures
                properties:
                  prefectures:
                    type: array
                    items:
                      "$ref": "#/components/schemas/prefecture"
  "/prefectures/{id}/cities":
    parameters:
      - name: id
        in: path
        required: true
        description: prefectureのid
        schema:
          type: integer
    get:
      tags:
        - city
      summary: 市長区村一覧
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - cities
                properties:
                  cities:
                    type: array
                    items:
                      "$ref": "#/components/schemas/city"
  "/companies":
    get:
      tags:
        - company
      summary: 会社一覧
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - companies
                properties:
                  companies:
                    type: array
                    items:
                      "$ref": "#/components/schemas/company"
    post:
      tags:
        - company
      summary: 会社作成
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/company_update"
      responses:
        "201":
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/company"
  "/companies/{id}":
    parameters:
      - name: id
        in: path
        required: true
        description: companyのid
        schema:
          type: integer
    get:
      summary: 会社詳細
      tags:
        - company
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/company"
    put:
      summary: 会社更新
      tags:
        - company
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/company_update"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/company"
  "/business_categories":
    get:
      tags:
        - business_category
      summary: 業種一覧
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - business_categories
                properties:
                  business_categories:
                    type: array
                    items:
                      "$ref": "#/components/schemas/business_category"
  "/admin/users":
    get:
      tags:
        - admin/user
      summary: ユーザー一覧
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - users
                properties:
                  users:
                    type: array
                    items:
                      "$ref": "#/components/schemas/user"
    post:
      tags:
        - admin/user
      summary: ユーザー作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - display_name
                - email
              properties:
                display_name:
                  type: string
                  description: ユーザー名
                  example: 田中太郎
                email:
                  type: string
                  description: email
                  example: taro.tanaka@example.com
                firebase_uid:
                  type: string
                  description: firebaseのuid
                  example: xxxxxxxxxxxxxxxxxxxx
      responses:
        "201":
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
  "/admin/users/{id}":
    parameters:
      - name: id
        in: path
        required: true
        description: userのid
        schema:
          type: integer
    get:
      summary: ユーザー詳細
      tags:
        - admin/user
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
    put:
      summary: ユーザー更新
      tags:
        - admin/user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - display_name
                - email
              properties:
                display_name:
                  type: string
                  description: ユーザー名
                  example: 田中太郎
                email:
                  type: string
                  description: email
                  example: taro.tanaka@example.com
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
components:
  schemas:
    subsidy:
      type: object
      required:
        - id
        - title
        - url
        - start_from
        - end_to
        - ministry
        - prefecture
        - city
      properties:
        id:
          type: integer
          description: id
          example: 1
        title:
          type: string
          description: 補助金名
          example: IT導入補助金
        url:
          type: string
          description: URL
          example: https://www.it-hojo.jp/applicant/
        subsidy_category:
          type: string
          description: 種類
          enum:
            - hojo
            - josei
        start_from:
          type: string
          format: date
          description: 募集期間（開始日）
          example: "2022-01-01"
        end_to:
          type: string
          format: date
          description: 募集期間（終了日）
          example: "2022-02-01"
        price_max:
          type: integer
          description: 最大支援金額
          example: 60000000
        support_ratio_min:
          type: string
          description: 支援割合（最小）
          example: 1/2
        support_ratio_max:
          type: string
          description: 支援割合（最大）
          example: 3/4
        level:
          type: integer
          description: 申請難易度
          example: 4
        deatil:
          type: string
          description: 詳細文章
          example: 新型コロナウイルス感染症の影響が長期化し、当面の需要や売上の回復が期待し難い中、ウィズコロナ・ポストコロナの時代の経済社会の変化に対応するために新分野展開、業態転換、事業・業種転換、事業再編又はこれらの取組を通じた規模の拡大等、思い切った事業再構築に意欲を有する中小企業等の挑戦を支援することで、日本経済の構造転換を促すことを目的とします。※申請の受付は11月17日より開始となりました。
        ministry:
          "$ref": "#/components/schemas/ministry"
        prefecture:
          "$ref": "#/components/schemas/prefecture"
        city:
          "$ref": "#/components/schemas/city"
        supplier_type:
          type: string
          description: 発行機関
          enum:
            - ministry
            - prefecture
            - city
        business_categories:
          type: array
          items:
            "$ref": "#/components/schemas/business_category"
        business_scales:
          type: array
          items:
            "$ref": "#/components/schemas/business_scale"
    ministry:
      type: object
      nullable: true
      required:
        - id
        - name
        - logo_url
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 省庁名
          example: 経済産業省
        logo_url:
          type: string
          description: URL
          example: https://example.com/logo.png
    prefecture:
      type: object
      nullable: true
      required:
        - id
        - name
        - logo_url
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 都道府県名
          example: 東京都
        logo_url:
          type: string
          description: URL
          example: https://example.com/logo.png
    city:
      type: object
      nullable: true
      required:
        - id
        - name
        - logo_url
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 市町区村名
          example: 千代田区
        logo_url:
          type: string
          description: URL
          example: https://example.com/logo.png
    business_category:
      type: object
      nullable: true
      required:
        - key
        - name
      properties:
        key:
          type: string
          description: enumのkey
          example: seizo
        name:
          type: string
          description: 業種名
          example: 製造業
    business_scale:
      type: string
      description: 事業規模
      enum:
        - small_business
        - small_and_medium
        - large
    company:
      type: object
      required:
        - id
        - name
        - capital
        - total_employee
        - business_scale
        - prefecture
        - city
      properties:
        id:
          type: integer
          description: id
          example: 1
        name:
          type: string
          description: 会社名
          example: つくば株式会社
        capital:
          type: integer
          description: 資本金
          example: 10000000
        total_employee:
          type: integer
          description: 従業員数
          example: 100
        business_scale:
          "$ref": "#/components/schemas/business_scale"
        prefecture:
          "$ref": "#/components/schemas/prefecture"
        city:
          "$ref": "#/components/schemas/city"
        business_categories:
          type: array
          items:
            "$ref": "#/components/schemas/business_category"
    company_update:
      type: object
      required:
        - name
        - capital
        - total_employee
        - business_scale
        - prefecture_id
        - city_id
        - business_categories
      properties:
        name:
          type: string
          description: 会社名
          example: つくば株式会社
        capital:
          type: integer
          description: 資本金
          example: 10000000
        total_employee:
          type: integer
          description: 従業員数
          example: 100
        business_scale:
          "$ref": "#/components/schemas/business_scale"
        prefecture_id:
          type: integer
          description: 都道府県ID
          example: 1
        city:
          type: integer
          description: 市長区村ID
          example: 1
        business_categories:
          type: array
          items:
            type: string
            description: 業種enum
            example: seizo
    user:
      type: object
      required:
        - id
        - display_name
        - email
        - firebase_uid
      properties:
        id:
          type: integer
          description: ユーザーID
          example: 1
        display_name:
          type: string
          description: ユーザー名
          example: 田中太郎
        email:
          type: string
          description: email
          example: taro.tanaka@example.com
        firebase_uid:
          type: string
          description: firebaseのuid
          example: xxxxxxxxxxxxxxxxxxxx
