default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: api_server_development

test:
  <<: *default
  database: api_server_test

production:
  <<: *default
  database: hojokin_dock_production
  username: <%= ENV["_PRODUCTION_DATABASE_USER"] %>
  password: <%= ENV['_PRODUCTION_DATABASE_PASSWORD'] %>
  socket: "/cloudsql/<%= ENV["_CLOUD_SQL_CONNECTION_NAME"] %>"
