AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "app/services/slack_service.rb"

Bundler/OrderedGems:
  Exclude:
    - "Gemfile"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
