service: default
runtime: ruby
env: flex
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
entrypoint: bundle exec rails server -p $PORT

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.7

env_variables:
  TZ: "Asia/Tokyo"
  RAILS_LOG_TO_STDOUT: "1"

beta_settings:
  cloud_sql_instances: macro-market-336309:asia-northeast1:hojokin-dock-production
