name: "Rails test"
on:
  push:
    paths:
      - 'api_server/**'
      - '.github/workflows/rails_test.yml'
jobs:
  rspec:
    defaults:
      run:
        working-directory: api_server
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RUBY_VERSION: 3.0.3
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports: ['3306:3306']
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
        working-directory: api_server
      - name: Database setup
        run: |
          mv config/database.ci.yml config/database.yml
          bundle exec rails db:setup
      - name: Run rspec
        run: bundle exec rspec --force-color --format progress
